name: Build and Push to build branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Prepare output
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      - name: Push build to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: .next/standalone
          publish_branch: build
          github_token: ${{ secrets.GITHUB_TOKEN }}
